//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WF2
{
    using System;
    using System.Collections.Generic;
    
    public partial class bab
    {
        public int id { get; set; }
        public int random { get; set; }
        public string dictionary { get; set; }
        public string text { get; set; }
        public string rpa { get; set; }
        public string cc { get; set; }
        public string dxp { get; set; }
        public string content { get; set; }
        public int ndoc { get; set; }
        public string xml { get; set; }
        public string extra { get; set; }
    
        public virtual bab_local bab_local { get; set; }
    }
}
