//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WF2
{
    using System;
    using System.Collections.Generic;
    
    public partial class bar_data
    {
        public int id { get; set; }
        public string dictionary { get; set; }
        public string text { get; set; }
    }
}
