//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WF2
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel;
    public partial class labels : INotifyPropertyChanged
    {
    	public event PropertyChangedEventHandler PropertyChanged;
    protected virtual void OnPropertyChanged(string propertyName)
    {
            PropertyChangedEventHandler handler = PropertyChanged;
            if (handler != null) handler(this, new PropertyChangedEventArgs(propertyName));
    }
    
    			private int _id;
    				public int id { get { return _id; } set { _id = value; OnPropertyChanged("id");} }
    						private string _tipolabel_tipo;
    				public string tipolabel_tipo { get { return _tipolabel_tipo; } set { _tipolabel_tipo = value; OnPropertyChanged("tipolabel_tipo");} }
    						private string _value;
    				public string value { get { return _value; } set { _value = value; OnPropertyChanged("value");} }
    						private Nullable<bool> _main;
    				public Nullable<bool> main { get { return _main; } set { _main = value; OnPropertyChanged("main");} }
    						private int _iter_id;
    				public int iter_id { get { return _iter_id; } set { _iter_id = value; OnPropertyChanged("iter_id");} }
    						private int _rowversion;
    				public int rowversion { get { return _rowversion; } set { _rowversion = value; OnPropertyChanged("rowversion");} }
    			}
}
