// Generated by .NET Reflector from C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\DevExpress.XtraLayout.v15.1\v4.0_15.1.8.0__b88d1754d700e49a\DevExpress.XtraLayout.v15.1.dll
namespace DevExpress.XtraDataLayout
{
    using DevExpress.Data;
    using DevExpress.Utils;
    using DevExpress.Utils.About;
    using DevExpress.XtraEditors;
    using DevExpress.XtraEditors.Controls;
    using DevExpress.XtraEditors.Repository;
    using DevExpress.XtraLayout;
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.Design;
    using System.Data;
    using System.Diagnostics;
    using System.Drawing;
    using System.Drawing.Design;
    using System.Threading;
    using System.Windows.Forms;

	//[ComplexBindingProperties("DataSource", "DataMember"), ToolboxTabName("DX.15.1: Navigation & Layout"), ToolboxBitmap(typeof(LayoutControl), "Images.datalayoutcontrol.bmp"), Designer("DevExpress.XtraDataLayout.DesignTime.DataLayoutDesigner, DevExpress.XtraLayout.v15.1.Design", typeof(IDesigner)), DXToolboxItem(DXToolboxItemKind.Free), LicenseProvider(typeof(DXWinFreeLicenseProvider)), Description("Provides advanced capabilities to create, customize and maintain a consistent layout for editing a specific data source's fields.")]
	public class DataLayoutControlExt : DataLayoutControl
	{

		public override LayoutElementsBindingInfo GetLayoutElementsBindingsInfo()
		{
			LayoutElementsBindingInfoHelperExt helper = new LayoutElementsBindingInfoHelperExt(this);
			LayoutElementsBindingInfo info = helper.CreateDataLayoutElementsBindingInfo();
			helper.FillWithSuggestedValues(info);
			return info;
		}
		/*
		protected override void OnDataSourceChanged()
		{
			try
			{
				this.DataControllerCore.SetListSource(this.BindingContext, this.DataSource, this.DataMember);
			}
			catch
			{
				this.DestroyDataController();
				ArrayList list = new ArrayList(base.Controls);
				foreach (Control control in list)
				{
					if (!((ILayoutDesignerMethods)this).IsInternalControl(control))
					{
						control.DataBindings.Clear();
					}
				}
				this.dataSource = null;
				this.dataMember = string.Empty;
				this.SetupDataController();
				if (base.DesignMode)
				{
					XtraMessageBox.Show("The data bindings of inner controls have been removed. The DataLayoutControl's DataSource and DataMember properties have been reset.", Localizer.Active.GetLocalizedString(StringId.CaptionError), MessageBoxButtons.OK, MessageBoxIcon.Hand);
				}
				return;
			}
			if ((this.AutoRetrieveFields && (base.Root.Items.Count == 0)) && !base.DesignMode)
			{
				this.RetrieveFields();
			}
		}
		*/
	}
}
