// Generated by .NET Reflector from C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\DevExpress.XtraLayout.v15.1\v4.0_15.1.8.0__b88d1754d700e49a\DevExpress.XtraLayout.v15.1.dll
namespace DevExpress.XtraDataLayout
{
    using DevExpress.Data;
    using DevExpress.Data.Utils;
    using System;
    using System.Runtime.CompilerServices;
    using System.Windows.Forms;
    
    public class LayoutElementBindingInfoExt : LayoutElementBindingInfo
	{
        public LayoutElementBindingInfoExt(DataColumnInfo dataColumanInfo) : base(dataColumanInfo)
        {
        }
        
        public LayoutElementBindingInfoExt(DataColumnInfo dataColumanInfo, System.Type editorType) : base(dataColumanInfo, editorType)
        {
        }
        
        public LayoutElementBindingInfoExt(DataColumnInfo dataColumanInfo, System.Type editorType, string boundPropertyName, bool visible) : base(dataColumanInfo, editorType, boundPropertyName, visible)
        {
        }

		public new LayoutElementsBindingInfo InnerLayoutElementsBindingInfo { get; set; }

		public new string DataMember { get; set; }
    }
}
